server:
  port: 8080

spring:
  application:
    name: spring-cloud-gateway-demo
  cloud:
    gateway:
      routes:
        - id: user-info-route
          uri: http://localhost:8080
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
            - ParameterEnrichment
            - RequestLogging
            - RemoveUserIdResponse

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway